permalink:           pretty
relative_permalinks: false

collections:
  articles:
    output: true
    permalink: /:path

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "article"